using System;
using System.Collections.Generic;
using UnityEngine;

namespace ChronoCore.Rewind
{
    public class RewindManager : MonoBehaviour
        {
                public static RewindManager Instance { get; private set; }

                        private const int BUFFER_CAPACITY = 540;
                                private const int MIN_REWIND_FRAMES = 6;

                                        private RewindFrame[] _buffer = new RewindFrame[BUFFER_CAPACITY];
                                                private int _head = 0;
                                                        private int _count = 0;
                                                                private List<IRewindable> _rewindables = new List<IRewindable>();

                                                                        public bool IsRewinding { get; private set; }
                                                                                public float BufferedSeconds => _count / 50.0f;

                                                                                        public event Action OnRewindStart;
                                                                                                public event Action OnRewindStop;

                                                                                                        private void Awake()
                                                                                                                {
                                                                                                                            if (Instance == null)
                                                                                                                                        {
                                                                                                                                                        Instance = this;
                                                                                                                                                                        DontDestroyOnLoad(gameObject);
                                                                                                                                                                                    }
                                                                                                                                                                                                else
                                                                                                                                                                                                            {
                                                                                                                                                                                                                            Destroy(gameObject);
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                        public void Register(IRewindable rewindable)
                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                            if (!_rewindables.Contains(rewindable))
                                                                                                                                                                                                                                                                                            _rewindables.Add(rewindable);
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                            public void Deregister(IRewindable rewindable)
                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                if (_rewindables.Contains(rewindable))
                                                                                                                                                                                                                                                                                                                                                _rewindables.Remove(rewindable);
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                public void OnRoomEntry(Vector2 entryPosition)
                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                    CaptureFrame(true, entryPosition);
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                    public void StartRewind()
                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                        if (IsRewinding || _count < MIN_REWIND_FRAMES) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                    IsRewinding = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                OnRewindStart?.Invoke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                public void StopRewind()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!IsRewinding) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                IsRewinding = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            OnRewindStop?.Invoke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private void FixedUpdate()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (IsRewinding) TickRewind();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else CaptureFrame(false, Vector2.zero);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private void CaptureFrame(bool isCheckpoint, Vector2 checkpointPos)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                RewindFrame frame = new RewindFrame
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            IsCheckpointFrame = isCheckpoint,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CheckpointPosition = checkpointPos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    foreach (var rewindable in _rewindables)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                frame.Snapshots[rewindable.GetRewindableId()] = rewindable.CaptureState();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _buffer[_head] = frame;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    _head = (_head + 1) % BUFFER_CAPACITY;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (_count < BUFFER_CAPACITY) _count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private void TickRewind()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (_count <= 0) { StopRewind(); return; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _head = (_head - 1 + BUFFER_CAPACITY) % BUFFER_CAPACITY;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            RewindFrame frame = _buffer[_head];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _count--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    foreach (var rewindable in _rewindables)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                string id = rewindable.GetRewindableId();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (frame.Snapshots.TryGetValue(id, out RewindSnapshot snapshot))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rewindable.RestoreState(snapshot);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (_count == 0) StopRewind();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
